### ISSUE TITLE
Question on R_matrix

### ISSUE THREAD

**Issue by pllee4** [markusbuchholz/Model-Predictive-Control-in-Cpp#1]
Hi @markusbuchholz ,

I wonder is there any impact for change in `R` for `R_matrix`.
```
MatrixXd R_matrix = Eigen::MatrixXd::Zero(horizon, horizon);
R_matrix.diagonal() = Eigen::VectorXd::Constant(horizon, R);
```

 I think right now changing value of `R` in the code won't change the response of the system?
(I guess is because the `control_errors` remains constant which is zero?)

**Comment by pllee4** [comment]
Side question:

For
```
for (int jj = 1; jj < horizon; jj++)
{
  predicted_states[jj] = A[0] * predicted_states[jj - 1] + B[0] * control_input;
}
```
,
is there any particular reason for not being `jj < horizon + 1` ? since `predicted_states` is having size of `horizon + 1`

**Comment by markusbuchholz** [comment]
@pllee4 Thanks for your question!

Since this is relatively old stuff to me, I cannot remember so many details. I cannot provide the correct reply to your side questions. Please make it correct.


This is my note as the article provides. Remember, the system is extremely simple; therefore, you cannot see differences as it affects the cost function.

### Impact of Changing R in MPC Cost Function

To address the impact of changing ```R ``` in  ```R_matrix``` and its effect on the system's response in MPC

#### Explanation of the Code

Our  code here initializes the ```R``` matrix as a diagonal matrix with the same value ```R ``` along the diagonal:

```cpp
MatrixXd R_matrix = Eigen::MatrixXd::Zero(horizon, horizon);
R_matrix.diagonal() = Eigen::VectorXd::Constant(horizon, R);
```

- ```horizon``` is the prediction horizon.
- ```R``` is the scalar value for each diagonal element of ```R_matrix```.

#### Impact of Changing R

Changing ```R``` will affect the system's response, even if the control error remains zero:

1. **Penalty on Control Inputs**: A higher ```R``` increases the penalty on control inputs, leading to more conservative actions. A lower ```R``` allows more aggressive actions.
2. **Control Effort vs. Performance Trade-off**: Increasing ```R``` prioritizes minimizing control effort, possibly causing larger deviations from the desired trajectory. Reducing ```R``` allows tighter tracking but increases control effort.

#### Example to Illustrate the Impact

Consider a system with a single control input and a prediction horizon of 3 (I program we have 0.5):

- With a high ```R``` value, the cost function heavily penalizes the control input, leading to more conservative control actions.
- With a low ```R ``` value, the cost function places much less penalty on the control input, allowing for more aggressive control actions.

#### I can summary

Changing ```R``` in our code alters the system's response by adjusting the trade-off between control effort and performance. Even with zero control error, control actions vary based on ```R ```, making it crucial to choose ```R``` based on your system's desired response characteristics.

Not sure if this is help you.


Check also here [link](https://aleksandarhaber.com/model-predictive-control-mpc-tutorial-1-unconstrained-formulation-derivation-and-implementation-in-python-from-scratch/)

**Comment by pllee4** [comment]
Thanks @markusbuchholz 

>I think right now changing value of R in the code won't change the response of the system?

I am raising the question because I realize changing of `R` in x_mpc_1_cpp.cpp from current 0.5f to 500.0f or any other value would result in the exact same response (given fixed value of `Q`), thus wondering why.

**Comment by markusbuchholz** [comment]
@pllee4 

Please check the ´´´x_mpc_1_cpp_fix.cpp´´'which solve the issues:

The original program did not correctly incorporate the control cost R into the optimization problem. This meant that changing R did not affect (as you noticed!!) the control inputs and the systems response.

In addition, there were issues with the dimensions of the matrices and vectors used in the optimization problem, affecting to incorrect calculations and crashes.

Thanks!

**Comment by pllee4** [comment]
Thanks for the fix!  @markusbuchholz 

with minor change to `A[0]` and `B[0]`, I saw there was impact for change in `R`

**Comment by markusbuchholz** [comment]
I close the issues since the simple fix has been elaborated.
